/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeBreadcrumb: typeof import('primevue/breadcrumb')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCalendar: typeof import('primevue/calendar')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeChart: typeof import('primevue/chart')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeDropdown: typeof import('primevue/dropdown')['default']
    PrimeFloatLabel: typeof import('primevue/floatlabel')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMessage: typeof import('primevue/message')['default']
    PrimeMultiSelect: typeof import('primevue/multiselect')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeTag: typeof import('primevue/tag')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    PrimeTree: typeof import('primevue/tree')['default']
  }
}
